### ISSUE TITLE
 uninitialized constant SJCL (NameError)

### ISSUE THREAD

**Issue by mabdelfattah** [mdp/sjcl_rb#1]
I was trying to use your sjcl gem in one of my rails apps, but the rails app fails to start and it shows the following error:

```
/usr/local/lib/ruby/gems/2.2.0/gems/sjcl-1.0.1/lib/sjcl/bit_array.rb:1:in `<top (required)>': uninitialized constant SJCL (NameError)
from /usr/local/lib/ruby/gems/2.2.0/gems/sjcl-1.0.1/lib/sjcl.rb:1:in `<top (required)>'
from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:76:in `require'
from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:72:in `each'
from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:72:in `block in require'
from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:61:in `each'
from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler/runtime.rb:61:in `require'
from /usr/local/lib/ruby/gems/2.2.0/gems/bundler-1.9.6/lib/bundler.rb:134:in `require'
from /app/config/application.rb:7:in `<top (required)>'
from /usr/local/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/commands.rb:39:in `require'
from /usr/local/lib/ruby/gems/2.2.0/gems/railties-3.2.22/lib/rails/commands.rb:39:in `<top (required)>'
from script/rails:6:in `require'
from script/rails:6:in `<main>'
```

**Comment by mdp** [comment]
Not sure what's happening here, but you may want to take a look at Gibberish instead. It's compatible with SJCL and it's much faster since built on OpenSSL - https://github.com/mdp/gibberish

I'm not actively maintaining this gem, but I'll try and take a look at this particular error when I get a chance.
